Adding an input to allow insecure SSL/TLS URLS
Jtalk/url-health-check-action pull request #23
Opened 2023-03-21 16:51 UTC by ScottMillard

This adds an input defaulted to `false` that when set to `true` will add the `--insecure` flag to the curl statement to allow insecure SSL URLs.

2023-03-25 09:34 UTC, Jtalk requested changes
Thanks for your contribution! 

If I may ask you to:
- run build and commit in the updated dist.js so that CI could run properly;
- add a test to cover the expected failure when accessing badssl with the new param left as default, to make sure GitHub won’t misinterpret “false” in action.yaml as “non-empty string, must be True” (been there, done that, not a picnic). 

Thanks!

2023-03-25 09:34 UTC, Jtalk commented on README.md
> +      allow-insecure: "false" # Optional, default is false
This should probably not be quoted, like the rest of the booleans above.

2024-01-29 22:07 UTC, closed without merging

2024-03-12 16:18 UTC, tobiasdenzler-nag commented
Is there a reason why this one is closed? I would be happy to see this functionality.

2024-04-05 16:57 UTC, Jtalk commented
Hey @tobiasdenzler-nag, Scott gave no reason for closing it, but I assume his circumstances had simply changed, and he was no longer in a position to finalise the PR.

I agree this functionality could be useful. Would you be interested in taking over this PR?